### ISSUE TITLE
kazma not open in archlinux kde

### ISSUE THREAD

**Issue by MOHAMED19OS** [sconts/kazam#35]
python --version                                                                                              
Python 3.8.0

`/usr/bin/kazam:32: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
WARNING Kazam - Failed to correctly detect operating system.
Traceback (most recent call last):
  File "/usr/bin/kazam", line 81, in <module>
    from kazam.version import *
ModuleNotFoundError: No module named 'kazam'`
'

**Comment by williamcanin** [comment]
I have the same problem :/

**Comment by bustEXZ** [comment]
same problem on archlinux :\

**Comment by ak-seyam** [comment]
i guess the problem might be in this [line](https://github.com/hzbd/kazam/blob/master/bin/kazam#L74) .plaform.linux_distribution() is deprecated and should be replaced with distro.linux_distribution(full_distribution_name=False)
