### ISSUE TITLE
Cannot save picture options v1.4.5/ubuntu

### ISSUE THREAD

**Issue by BCsabaEngine** [sconts/kazam#67]
I use Kazam v1.4.5 on Ubuntu. Cannot setup picture folder and filename prefix, because it is not saved with Preferences window. Always show and use "MyFolder" and "katam_screencast_" settings.

**Comment by niknah** [comment]
Not working in the version here.

I know it works with this other fork here...

```
https://github.com/niknah/kazam.git
cd kazam.git
bash bin/run_local_dev.sh
```
