### ISSUE TITLE
Save the recording with yuv420p ?

### ISSUE THREAD

**Issue by jinboson** [sconts/kazam#69]
Hi,
When recording with h264, the default pixel formats is yuv444p, which can not be played on some devices such as wechat. Is it possible to save the recording with yuv420p ? Any suggestions?
Thanks.

**Comment by niknah** [comment]
You can use the fork here...  
https://github.com/niknah/kazam

In the preferences is an option there to use i420 for the recording.

**Comment by jinboson** [comment]
I tried, but it failed when enabling I420. With command line ./kazam --debug, it output error messages:
`DEBUG Main - Starting counter.
DEBUG Main - Hiding main window.
DEBUG Main - Ubuntu 13.04 or higher not detected, recording outline not shown.
DEBUG Main - Counter finished.
DEBUG Indicator - Recording started.
DEBUG GStreamer - Setting STATE_PLAYING
DEBUG GStreamer - Received an error message: gstx264enc.c(1906): gst_x264_enc_init_encoder (): /GstPipeline:pipeline0/GstX264Enc:video_encoder
DEBUG GStreamer - Sending new EOS event
DEBUG Main - Stop request.
DEBUG GStreamer - Sending new EOS event
`
it's gstreamer problem ?

**Comment by niknah** [comment]
To see the full error, run it with...
GST_DEBUG=7 ./kazam --debug

Check that it is the latest revision.   I made a change a few days ago to fix a problem with odd numbered width/heights.

**Comment by jinboson** [comment]
Yeah, it's the latest version. The log is:
[log.txt](https://github.com/hzbd/kazam/files/7778064/log.txt)

**Comment by niknah** [comment]
The error looks like...
x264enc :0::<video_encoder>ESC[00m width not divisible by 2 (1919x1079)

Which I thought I fixed in the last revision.  The way around is to click "area" and pick an error on the screen that's an even numbered width in pixels.

**Comment by jinboson** [comment]
ok, thanks!
