### ISSUE TITLE
Failed to correctly detect operating system.

### ISSUE THREAD

**Issue by mrbardia72** [sconts/kazam#76]
WARNING Kazam - Failed to correctly detect operating system.
kazam 1.4.5 'NCC-80102'

why?

**Comment by niknah** [comment]
They removed platform.linux_distribution from the the latest version of python.  Just a warning, it will default to Ubuntu if it can't find the operating system.

**Comment by mrbardia72** [comment]
My version Ubuntu is 22.04
My problem now is that when the recording is over I only have sound, in fact I only have a black screen
